BasketContent, handle case where yearly avg price is nil
```
NoMethodError: undefined method `-' for nil:NilClass

    diff = price - base_price
                 ^
  from app/helpers/basket_contents_helper.rb:60:in `display_basket_price_diff'
  from arbre (1.5.0) lib/arbre/element.rb:183:in `method_missing'
  from arbre (1.5.0) lib/arbre/context.rb:83:in `method_missing'
  from app/views/active_admin/basket_contents/_prices.html.arb:8
  from arbre (1.5.0) lib/arbre/element/builder_methods.rb:32:in `block in build_tag'
  from arbre (1.5.0) lib/arbre/context.rb:94:in `with_current_arbre_element'
  from arbre (1.5.0) lib/arbre/element/builder_methods.rb:27:in `build_tag'
  from arbre (1.5.0) lib/arbre/element/builder_methods.rb:40:in `insert_tag'
  from arbre (1.5.0) lib/arbre/element/builder_methods.rb:15:in `div'
  from app/views/active_admin/basket_contents/_prices.html.arb:4
  from app/views/active_admin/basket_contents/_prices.html.arb:2:in `each'
  from app/views/active_admin/basket_contents/_prices.html.arb:2
  from arbre (1.5.0) lib/arbre/context.rb:47:in `instance_eval'
  from arbre (1.5.0) lib/arbre/context.rb:47:in `initialize'
  from app/views/active_admin/basket_contents/_prices.html.arb:1:in `new'
  from app/views/active_admin/basket_contents/_prices.html.arb:1
```

https://sentry.io/organizations/acp-admin/issues/3223643211