Bug fix, when comparing prices, convert to float first
https://acp-admin.sentry.io/issues/4447012189

```
TypeError: nil can't be coerced into Float (TypeError)

      before.zip(after).map { |b, a| (b - a).abs }
                                          ^
  from app/models/checker/delivery_basket_content_avg_prices.rb:32:in `-'
  from app/models/checker/delivery_basket_content_avg_prices.rb:32:in `block in diffs'
  from app/models/checker/delivery_basket_content_avg_prices.rb:32:in `map'
  from app/models/checker/delivery_basket_content_avg_prices.rb:32:in `diffs'
  from app/models/checker/delivery_basket_content_avg_prices.rb:20:in `check!'
  from app/models/checker/delivery_basket_content_avg_prices.rb:7:in `block in check_all!'
  from activerecord (7.0.7.2) lib/active_record/relation/batches.rb:71:in `each'
  from activerecord (7.0.7.2) lib/active_record/relation/batches.rb:71:in `block in find_each'
  from activerecord (7.0.7.2) lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
  from activerecord (7.0.7.2) lib/active_record/relation/batches.rb:245:in `block in in_batches'
  from activerecord (7.0.7.2) lib/active_record/relation/batches.rb:229:in `loop'
  from activerecord (7.0.7.2) lib/active_record/relation/batches.rb:229:in `in_batches'
  from activerecord (7.0.7.2) lib/active_record/relation/batches.rb:137:in `find_in_batches'
  from activerecord (7.0.7.2) lib/active_record/relation/batches.rb:70:in `find_each'
  from app/models/checker/delivery_basket_content_avg_prices.rb:6:in `check_all!'
  from app/jobs/scheduled/daily_job.rb:11:in `perform'
  from activejob (7.0.7.2) lib/active_job/execution.rb:65:in `block in _perform_job'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
  from activesupport (7.0.7.2) lib/active_support/current_attributes.rb:205:in `set'
  from activesupport (7.0.7.2) lib/active_support/current_attributes.rb:147:in `set'
  from app/jobs/concerns/current_context.rb:8:in `block (3 levels) in <module:CurrentContext>'
  from lib/tenant.rb:28:in `switch'
  from app/jobs/concerns/current_context.rb:6:in `block (2 levels) in <module:CurrentContext>'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `instance_exec'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
  from i18n (1.14.1) lib/i18n.rb:322:in `with_locale'
  from activejob (7.0.7.2) lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `instance_exec'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
  from activesupport (7.0.7.2) lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
  from activejob (7.0.7.2) lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `instance_exec'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:138:in `run_callbacks'
  from activejob (7.0.7.2) lib/active_job/execution.rb:64:in `_perform_job'
  from activejob (7.0.7.2) lib/active_job/instrumentation.rb:20:in `_perform_job'
  from activejob (7.0.7.2) lib/active_job/execution.rb:52:in `perform_now'
  from activejob (7.0.7.2) lib/active_job/instrumentation.rb:14:in `block in perform_now'
  from activejob (7.0.7.2) lib/active_job/instrumentation.rb:25:in `block in instrument'
  from activesupport (7.0.7.2) lib/active_support/notifications.rb:206:in `block in instrument'
  from activesupport (7.0.7.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from sentry-rails (5.10.0) lib/sentry/rails/tracing.rb:54:in `instrument'
  from activesupport (7.0.7.2) lib/active_support/notifications.rb:206:in `instrument'
  from activejob (7.0.7.2) lib/active_job/instrumentation.rb:35:in `instrument'
  from activejob (7.0.7.2) lib/active_job/instrumentation.rb:14:in `perform_now'
  from activejob (7.0.7.2) lib/active_job/logging.rb:18:in `block in perform_now'
  from activesupport (7.0.7.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
  from activesupport (7.0.7.2) lib/active_support/tagged_logging.rb:37:in `tagged'
  from activesupport (7.0.7.2) lib/active_support/tagged_logging.rb:99:in `tagged'
  from activejob (7.0.7.2) lib/active_job/logging.rb:25:in `tag_logger'
  from activejob (7.0.7.2) lib/active_job/logging.rb:18:in `perform_now'
  from sentry-rails (5.10.0) lib/sentry/rails/active_job.rb:6:in `perform_now'
  from activejob (7.0.7.2) lib/active_job/execution.rb:30:in `block in execute'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
  from activejob (7.0.7.2) lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
  from activesupport (7.0.7.2) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.0.7.2) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (7.0.7.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (7.0.7.2) lib/active_support/reloader.rb:71:in `wrap'
  from activejob (7.0.7.2) lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `instance_exec'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
  from activesupport (7.0.7.2) lib/active_support/callbacks.rb:138:in `run_callbacks'
  from activejob (7.0.7.2) lib/active_job/execution.rb:28:in `execute'
  from activejob (7.0.7.2) lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:209:in `execute_job'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:177:in `block (2 levels) in process'
  from sidekiq (7.1.2) lib/sidekiq/middleware/chain.rb:180:in `traverse'
  from sidekiq (7.1.2) lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
  from sentry-sidekiq (5.10.0) lib/sentry/sidekiq/sentry_context_middleware.rb:26:in `call'
  from sidekiq (7.1.2) lib/sidekiq/middleware/chain.rb:182:in `traverse'
  from sidekiq (7.1.2) lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
  from sidekiq (7.1.2) lib/sidekiq/metrics/tracking.rb:26:in `track'
  from sidekiq (7.1.2) lib/sidekiq/metrics/tracking.rb:122:in `call'
  from sidekiq (7.1.2) lib/sidekiq/middleware/chain.rb:182:in `traverse'
  from sidekiq (7.1.2) lib/sidekiq/middleware/chain.rb:173:in `invoke'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:176:in `block in process'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
  from sidekiq (7.1.2) lib/sidekiq/job_retry.rb:114:in `local'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
  from sidekiq (7.1.2) lib/sidekiq/rails.rb:16:in `block in call'
  from activesupport (7.0.7.2) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.0.7.2) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (7.0.7.2) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.0.7.2) lib/active_support/reloader.rb:71:in `wrap'
  from sidekiq (7.1.2) lib/sidekiq/rails.rb:15:in `call'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:270:in `stats'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
  from sidekiq (7.1.2) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
  from sidekiq (7.1.2) lib/sidekiq/job_retry.rb:81:in `global'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:128:in `block in dispatch'
  from sidekiq (7.1.2) lib/sidekiq/job_logger.rb:39:in `prepare'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:127:in `dispatch'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:175:in `process'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:82:in `process_one'
  from sidekiq (7.1.2) lib/sidekiq/processor.rb:72:in `run'
  from sidekiq (7.1.2) lib/sidekiq/component.rb:10:in `watchdog'
  from sidekiq (7.1.2) lib/sidekiq/component.rb:19:in `block in safe_thread'
```